(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const fields=[['product','Produs'],['km','Kilometri'],['tons','Tone'],['client','Client'],['measure','Măsurări'],['status','Stadiu'],['notes','Observații']];
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=x=>Number(String(x||'0').replace(',','.'))||0;
  const fmt=x=>x.toLocaleString('ro-RO',{maximumFractionDigits:3});
  const blank=material=>Object.fromEntries([['material',material],...fields.map(([k])=>[k,''])]);
  let rows=[blank('AL')],reviewFields=new Set(),needsReview=false,loadedId=null,importBusy=false,undo=null,identityRevision=0;
  $('forecast-date').value=new Date().toLocaleDateString('sv-SE');
  function totals(){const sum=m=>rows.filter(r=>r.material===m).reduce((a,r)=>({km:a.km+num(r.km),tons:a.tons+num(r.tons)}),{km:0,tons:0});const a=sum('AL'),c=sum('CU');$('forecast-totals').innerHTML=`<div><span>Total AL</span><strong>${fmt(a.km)} km · ${fmt(a.tons)} t</strong></div><div><span>Total CU</span><strong>${fmt(c.km)} km · ${fmt(c.tons)} t</strong></div><div><span>Total general</span><strong>${fmt(a.km+c.km)} km · ${fmt(a.tons+c.tons)} t</strong></div>`;}
  function render(){
    $('forecast-rows').innerHTML=['AL','CU'].map(material=>`<div class="plan-group"><h3>${material==='AL'?'Aluminiu':'Cupru'} <small>${rows.filter(r=>r.material===material).length} rânduri</small></h3>${rows.map((r,i)=>r.material!==material?'':`<article class="plan-row"><div class="plan-row-head"><strong>${material} · poziția ${rows.slice(0,i+1).filter(x=>x.material===material).length}</strong><button type="button" data-remove="${i}" aria-label="Șterge rândul ${i+1}">Șterge</button></div><div class="plan-field-grid">${fields.map(([key,label])=>`<label class="plan-field ${reviewFields.has(i+':'+key)?'needs-review':''}"><span>${label}${reviewFields.has(i+':'+key)?' · verifică':''}</span><input data-index="${i}" data-key="${key}" type="text" ${['km','tons'].includes(key)?'inputmode="decimal"':'autocomplete="off"'} maxlength="120" value="${esc(r[key])}" placeholder="${['km','tons'].includes(key)?'0,00':'—'}"></label>`).join('')}</div></article>`).join('')}</div>`).join('');totals();
  }
  $('forecast-rows').addEventListener('input',e=>{const input=e.target;if(!input.matches('[data-key]'))return;const key=input.dataset.key,i=+input.dataset.index,raw=input.value.trim();if(['km','tons'].includes(key)&&raw&&!/^\d{0,7}(?:[.,]\d{0,4})?$/.test(raw)){input.value=rows[i][key];$('forecast-status').textContent='Valoare neacceptată. Folosește un număr pozitiv, cu virgulă sau punct și cel mult 4 zecimale.';return;}rows[i][key]=raw;reviewFields.delete(i+':'+key);input.closest('.plan-field').classList.remove('needs-review');totals();});
  $('forecast-rows').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;const index=+b.dataset.remove;undo={index,row:{...rows[index]},review:new Set(reviewFields)};rows.splice(index,1);reviewFields.clear();$('undo-forecast-row').hidden=false;render();});
  $('undo-forecast-row').addEventListener('click',()=>{if(!undo)return;rows.splice(undo.index,0,undo.row);reviewFields=undo.review;undo=null;$('undo-forecast-row').hidden=true;render();$('forecast-status').textContent='Rândul a fost restaurat.';});
  for(const [id,m] of [['forecast-add-al','AL'],['forecast-add-cu','CU']])$(id).addEventListener('click',()=>{rows.push(blank(m));render();document.querySelector(`#forecast-rows [data-index="${rows.length-1}"][data-key="product"]`)?.focus();});
  function payload(){return {mode:'forecast',date:$('forecast-date').value,rows:rows.map(r=>Object.fromEntries([['material',r.material],...fields.map(([key])=>[key,r[key]??''])]))};}
  async function request(url,method='POST'){const response=await window.PLUPFetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload()),credentials:'same-origin'});if(!response.ok){const err=await response.json().catch(()=>({}));throw Error(err.error||'Operația nu a reușit.');}return response;}
  function reviewed(){if(needsReview&&!$('forecast-confirm').checked){$('forecast-status').textContent='Compară datele cu imaginea și bifează confirmarea.';$('forecast-review').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});return false;}return true;}
  $('forecast-save').addEventListener('click',async()=>{if(!reviewed())return;const submitted=JSON.stringify(payload()),revision=identityRevision,b=$('forecast-save');b.disabled=true;$('forecast-status').textContent='Se salvează…';try{const result=await (await request(loadedId?'/api/reports/'+encodeURIComponent(loadedId):'/api/reports',loadedId?'PUT':'POST')).json();if(revision!==identityRevision)return;loadedId=result.id;window.PLUPSmart?.saved('forecast',loadedId,submitted);$('forecast-status').textContent='Previzul a fost salvat în istoric.';}catch(e){$('forecast-status').textContent=e.message;}finally{b.disabled=false;}});
  $('forecast-image').addEventListener('click',async()=>{if(!reviewed())return;const exportPayload=JSON.stringify(payload()),revision=identityRevision,exportDate=$('forecast-date').value,b=$('forecast-image');b.disabled=true;$('forecast-status').textContent='Se generează imaginea…';try{const theme=window.PLUPTheme.current(),show=$('forecast-show-status').checked,response=await request(`/api/render?theme=${theme}&status=${show?'1':'0'}`),blob=await response.blob();if(revision!==identityRevision)return;if(JSON.stringify(payload())!==exportPayload)throw Error('Datele au fost schimbate în timpul generării. Generează din nou imaginea.');if(blob.type!=='image/png')throw Error('Răspuns imagine invalid.');const url=URL.createObjectURL(blob),wrap=document.createElement('div'),img=document.createElement('img'),link=document.createElement('a');wrap.className='image-result';img.src=url;img.alt='Previz zilnic PLUP';link.href=url;link.download=`NRG_PLUP_previz_${exportDate}_${show?'productie':'directiune'}_${theme}.png`;link.textContent='Descarcă PNG ↓';wrap.append(img,link);window.PLUPUI.clearImages($('forecast-images'));$('forecast-images').replaceChildren(wrap);$('forecast-status').textContent='Imaginea este gata. Pe iPhone poți apăsa lung pe ea pentru salvare.';}catch(e){$('forecast-status').textContent=e.message;}finally{b.disabled=false;}});
  async function imagePayload(file){
    if(file.size>20_000_000)throw Error('Imaginea depășește 20 MB.');
    const url=URL.createObjectURL(file),photo=new Image();
    try{photo.src=url;await photo.decode();if(photo.naturalWidth*photo.naturalHeight>30_000_000)throw Error('Rezoluția depășește 30 megapixeli.');const scale=Math.min(1,3000/photo.naturalWidth,3000/photo.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.round(photo.naturalWidth*scale);canvas.height=Math.round(photo.naturalHeight*scale);canvas.getContext('2d').drawImage(photo,0,0,canvas.width,canvas.height);let blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(blob?.size>6_000_000)blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob||blob.size>6_000_000)throw Error('Imaginea pregătită depășește 6 MB.');return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Nu am putut citi imaginea.'));reader.readAsDataURL(blob);});}finally{URL.revokeObjectURL(url);}
  }
  async function importImage(file){if(importBusy)return;if(rows.some(r=>fields.some(([key])=>String(r[key]??'').trim()))&&!window.confirm('Importul înlocuiește rândurile din formular. Continui?'))return;const importRevision=identityRevision;importBusy=true;$('forecast-file').disabled=true;$('forecast-paste').disabled=true;$('forecast-status').textContent='Citesc imaginea…';try{const image=await imagePayload(file),response=await window.PLUPFetch('/api/forecast/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image}),credentials:'same-origin'}),draft=await response.json();if(!response.ok)throw Error(draft.error||'Nu am putut citi previzul.');if(importRevision!==identityRevision)return;identityRevision++;rows=draft.rows;loadedId=null;undo=null;$('undo-forecast-row').hidden=true;window.PLUPUI.markDirty('forecast');reviewFields=new Set(draft.review.map(item=>item.row+':'+item.field));if(draft.date)$('forecast-date').value=draft.date;needsReview=true;$('forecast-confirm').checked=false;$('forecast-review').hidden=false;$('forecast-review-message').textContent=`Am extras ${rows.length} rânduri. ${reviewFields.size} câmpuri trebuie verificate. ${draft.message||''}`;render();window.PLUPSmart?.showImport('forecast',file,payload(),[...reviewFields]);$('forecast-status').textContent='Datele au fost adăugate în formular; imaginea nu este păstrată.';$('forecast-review').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}catch(e){$('forecast-status').textContent=e.message;}finally{importBusy=false;$('forecast-file').disabled=false;$('forecast-paste').disabled=false;}}
  $('forecast-file').addEventListener('change',async e=>{const f=e.target.files?.[0];if(f)await importImage(f);e.target.value='';});
  $('forecast-paste').addEventListener('click',async()=>{if(!navigator.clipboard?.read){$('forecast-status').textContent='Ține apăsat în caseta de lipire și alege „Lipește”.';$('forecast-paste-zone').focus();return;}try{const items=await navigator.clipboard.read();for(const item of items){const kind=item.types.find(type=>type.startsWith('image/'));if(kind){await importImage(await item.getType(kind));return;}}$('forecast-status').textContent='Clipboardul nu conține o imagine.';}catch{$('forecast-status').textContent='Accesul la clipboard nu a fost permis. Lipește direct în casetă.';$('forecast-paste-zone').focus();}});
  document.addEventListener('paste',e=>{if($('forecast-view').hidden)return;const file=Array.from(e.clipboardData?.items||[]).find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();void importImage(file);}else if(e.target===$('forecast-paste-zone')){e.preventDefault();$('forecast-status').textContent='Clipboardul nu conține o imagine.';}});
  $('forecast-paste-zone').addEventListener('beforeinput',e=>{if(e.inputType!=='insertFromPaste')e.preventDefault();});
  $('forecast-paste-zone').addEventListener('blur',()=>{$('forecast-paste-zone').textContent='Pe iPhone, ține apăsat aici și alege „Lipește”. Pe PC poți apăsa Ctrl+V sau ⌘V.';});
  window.PLUPForecast={load(data,id){identityRevision++;undo=null;$('undo-forecast-row').hidden=true;$('forecast-date').value=data.date;rows=data.rows.map(r=>({...blank(r.material),...r}));loadedId=id;reviewFields.clear();needsReview=false;$('forecast-review').hidden=true;window.PLUPUI.clearImages($('forecast-images'));render();},revision:()=>identityRevision,draft(){return {payload:payload(),metadata:{id:loadedId,needsReview:needsReview,review:[...reviewFields],showStatus:$('forecast-show-status').checked}};},restoreDraft(data){window.PLUPForecast.load(data.payload,data.metadata.id);needsReview=!!data.metadata.needsReview;reviewFields=new Set(data.metadata.review||[]);$('forecast-confirm').checked=false;$('forecast-review').hidden=!needsReview;$('forecast-review-message').textContent='Ciornă importată: verifică datele cu imaginea sursă înainte de confirmare. Imaginea nu se păstrează după închiderea paginii.';$('forecast-show-status').checked=data.metadata.showStatus!==false;render();},payload};
  render();
})();
