(() => {
  'use strict';
  const fields=[['client','Client','text'],['product','Produs','text'],['planned','Metal planificat (t)','decimal'],['handed','Metal predat (t)','decimal'],['wire','Sârmă (t)','decimal'],['spool','Stoc lită (t)','decimal'],['bar','Stoc fune / bară (km)','decimal'],['vane','Stoc vane (km)','decimal'],['cable','Stoc cablat (km)','decimal'],['mi','Stoc M.I. (km)','decimal'],['armored','Stoc armat (km)','decimal'],['mf','Stoc M.F. (km)','decimal'],['goods','Marfă predată (km)','decimal'],['notes','Observații','text']];
  const number=x=>Number(String(x||'0').replace(',','.'))||0;
  const fmt=x=>x.toLocaleString('ro-RO',{minimumFractionDigits:2,maximumFractionDigits:2});
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const $=id=>document.getElementById(id);
  let rows=[{material:'AL',client:'',product:''},{material:'CU',client:'',product:''}];
  $('plan-date').value=new Date().toLocaleDateString('sv-SE');
  function render(){
    $('plan-rows').innerHTML=['AL','CU'].map(material=>`<div class="plan-group"><h3>${material==='AL'?'Aluminiu':'Cupru'} <small>${rows.filter(r=>r.material===material).length} rânduri</small></h3>${rows.map((r,i)=>r.material!==material?'':`<article class="plan-row"><div class="plan-row-head"><strong>${material} · poziția ${rows.slice(0,i+1).filter(x=>x.material===material).length}</strong><button type="button" data-remove="${i}" aria-label="Șterge rândul ${i+1}">Șterge</button></div><div class="plan-field-grid">${fields.map(([key,label,type])=>`<label class="plan-field"><span>${label}</span><input data-index="${i}" data-key="${key}" type="text" ${type==='decimal'?'inputmode="decimal"':'autocomplete="off"'} maxlength="120" value="${esc(r[key])}" placeholder="${type==='decimal'?'0,00':'—'}"></label>`).join('')}</div></article>`).join('')}</div>`).join('');
    totals();
  }
  function totals(){const sum=material=>rows.filter(r=>r.material===material).reduce((a,r)=>{for(const k of ['planned','handed','wire'])a[k]+=number(r[k]);return a},{planned:0,handed:0,wire:0});const al=sum('AL'),cu=sum('CU');$('plan-totals').innerHTML=`<div><span>Total AL planificat / predat</span><strong>${fmt(al.planned)} / ${fmt(al.handed)} t</strong></div><div><span>Total CU planificat / predat</span><strong>${fmt(cu.planned)} / ${fmt(cu.handed)} t</strong></div><div><span>Total general planificat / predat</span><strong>${fmt(al.planned+cu.planned)} / ${fmt(al.handed+cu.handed)} t</strong></div>`;}
  $('plan-rows').addEventListener('input',e=>{const input=e.target;if(!input.matches('[data-key]'))return;const key=input.dataset.key;const raw=input.value.trim();if(fields.find(f=>f[0]===key)?.[2]==='decimal'&&raw&&!/^\d{0,7}(?:[.,]\d{0,4})?$/.test(raw)){input.value=rows[+input.dataset.index][key]??'';return;}rows[+input.dataset.index][key]=raw;totals();});
  $('plan-rows').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;rows.splice(+b.dataset.remove,1);render();});
  for(const [id,material] of [['add-al','AL'],['add-cu','CU']])$(id).addEventListener('click',()=>{rows.push({material});render();document.querySelector(`[data-index="${rows.length-1}"][data-key="client"]`)?.focus();});
  function payload(){return {mode:'plan',date:$('plan-date').value,week:$('plan-week').value.trim(),incoming:$('plan-incoming').value.trim(),rows:rows.map(r=>Object.fromEntries([['material',r.material],...fields.map(([key])=>[key,r[key]??''])]))};}
  async function post(path){const response=await window.PLUPFetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload()),credentials:'same-origin'});if(!response.ok){const e=await response.json().catch(()=>({}));throw Error(e.error||'Operația nu a reușit.');}return response;}
  $('save-plan').addEventListener('click',async()=>{const b=$('save-plan');b.disabled=true;$('plan-status').textContent='Se salvează…';try{await post('/api/reports');$('plan-status').textContent='Planul a fost salvat în istoric.';}catch(e){$('plan-status').textContent=e.message;}finally{b.disabled=false;}});
  $('image-plan').addEventListener('click',async()=>{const b=$('image-plan');b.disabled=true;$('plan-status').textContent='Se generează imaginea…';try{const response=await post('/api/render'),blob=await response.blob();if(blob.type!=='image/png')throw Error('Răspuns imagine invalid.');const url=URL.createObjectURL(blob),wrap=document.createElement('div'),img=document.createElement('img'),link=document.createElement('a');wrap.className='image-result';img.src=url;img.alt='Previzualizare plan PLUP';link.href=url;link.download=`NRG_PLUP_plan_${$('plan-date').value}.png`;link.textContent='Descarcă PNG ↓';wrap.append(img,link);$('plan-images').replaceChildren(wrap);$('plan-status').textContent='Imaginea este gata. Pe iPhone, poți apăsa lung pe ea pentru a o salva.';}catch(e){$('plan-status').textContent=e.message;}finally{b.disabled=false;}});
  window.PLUPPlan={load(data){$('plan-date').value=data.date;$('plan-week').value=data.week;$('plan-incoming').value=data.incoming||'';rows=data.rows;render();},payload};
  render();
})();
