(() => {
 'use strict';
 const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={weekday:'Raport zilnic',weekend:'Raport 3 zile',plan:'Plan de producție',forecast:'Previz zilnic'},fmt=(n,d=2)=>Number(n||0).toLocaleString('ro-RO',{maximumFractionDigits:d});
 const today=()=>new Date().toLocaleDateString('sv-SE'),controller=m=>m==='plan'?window.PLUPPlan:m==='forecast'?window.PLUPForecast:window.PLUPReport;
 const active=()=>{let m=window.PLUPDashboard.current();if(['weekday','weekend'].includes(m))m=window.PLUPReport.payload().mode;return Object.hasOwn(names,m)?m:null;};
 const drafts=new Map(),local=new Map(),times=new Map(),timers=new Map(),pending=new Map(),imports=new Map(),paused=new Set();let home=null,refreshing=0,catalog=[];
 const key=m=>'plup-draft-v1-'+m;
 for(const mode of Object.keys(names)){try{const d=JSON.parse(localStorage.getItem(key(mode))||'null');if(d?.payload?.mode===mode)local.set(mode,d);}catch{}}
 const authReady=()=>$('login-gate').hidden;
 async function request(url,options={}){const r=await window.PLUPFetch(url,{credentials:'same-origin',...options});const data=await r.json();if(!r.ok)throw Error(data.error||'Operația nu a reușit.');return data;}
 const post=(url,body)=>request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 function status(mode,message){const node=$(mode==='weekday'||mode==='weekend'?'smart-draft-report':'smart-draft-'+mode);if(node)node.textContent=message;}
 function snapshot(mode){const d=controller(mode).draft();if(d.payload.mode!==mode)return null;d.metadata.version=d.metadata.id?window.PLUPDashboard.getVersion(d.metadata.id):null;return d;}
 function schedule(mode){if(!mode||!authReady())return;const d=snapshot(mode);if(!d)return;d.updated_at=new Date().toISOString();local.set(mode,d);try{localStorage.setItem(key(mode),JSON.stringify(d));}catch{status(mode,'Stocarea locală nu este disponibilă. Se încearcă salvarea pe server.');}clearTimeout(timers.get(mode));status(mode,'Ciornă locală · se sincronizează…');if(!paused.has(mode))timers.set(mode,setTimeout(()=>sync(mode),1000));}
 async function sync(mode){if(pending.has(mode)||paused.has(mode))return;const d=local.get(mode);if(!d||!authReady())return;const fingerprint=JSON.stringify(d),expected=times.get(mode)??null;
  const task=(async()=>{try{const result=await post('/api/smart/draft',{payload:d.payload,metadata:d.metadata,expected});times.set(mode,result.updated_at);drafts.set(mode,{...d,updated_at:result.updated_at});status(mode,'Ciornă sincronizată · '+new Date(result.updated_at).toLocaleTimeString('ro-RO'));}catch(e){status(mode,'Copia locală este păstrată. '+e.message);}finally{pending.delete(mode);if(local.has(mode)&&JSON.stringify(local.get(mode))!==fingerprint)void sync(mode);}})();pending.set(mode,task);await task;
 }
 function saved(mode,id,submitted){times.delete(mode);drafts.delete(mode);if(submitted&&JSON.stringify(controller(mode).payload())!==submitted){schedule(mode);return;}clearTimeout(timers.get(mode));local.delete(mode);drafts.delete(mode);times.delete(mode);try{localStorage.removeItem(key(mode));}catch{}status(mode,'Raport salvat în istoric. Următoarele modificări vor forma o ciornă nouă.');void refresh();}
 function drawDrafts(){const combined=new Map(drafts);for(const [m,d] of local){if(!combined.has(m)||d.updated_at>combined.get(m).updated_at)combined.set(m,d);} $('smart-drafts').innerHTML=[...combined].map(([m,d])=>`<div class="smart-record"><div><strong>${esc(names[m])}</strong><span>${esc(d.payload.date)} · ${esc(new Date(d.updated_at).toLocaleString('ro-RO'))}${local.has(m)&&!drafts.has(m)?' · local':''}</span></div><button class="secondary-button" type="button" data-resume="${m}">Continuă</button></div>`).join('')||'<p>Nicio ciornă în lucru.</p>';}
 async function refresh(){if(!authReady())return;const rev=++refreshing;$('smart-dashboard-status').textContent='Se actualizează activitatea…';try{const [data,savedDrafts]=await Promise.all([request(`/api/smart/dashboard?date=${today()}&days=${$('smart-period').value}`),request('/api/smart/drafts')]);if(rev!==refreshing)return;home=data;catalog=data.catalog;drafts.clear();for(const d of savedDrafts){drafts.set(d.mode,d);times.set(d.mode,d.updated_at);}drawDrafts();drawHome();$('smart-dashboard-status').textContent='Date din rapoartele finale salvate. Ciornele nu intră în totaluri.';}catch(e){if(rev===refreshing){$('smart-dashboard-status').textContent=e.message;drawDrafts();}}}
 function drawHome(){const current=home.current,prev=home.previous;const comparison=(a,b,unit)=>prev.count?`Față de perioada anterioară: ${Number(a)>=Number(b)?'+':''}${fmt(Number(a)-Number(b))} ${unit}`:'Nu există rapoarte în perioada anterioară.';
  $('smart-kpis').innerHTML=[['Total predat',current.handed,'t',prev.handed],['Backlog predat',current.backlog,'t',prev.backlog],['Deșeu',current.percent,'%',prev.percent]].map(([label,value,unit,previous])=>`<article class="smart-kpi"><span>${label}</span><strong>${current.count?fmt(value):'—'} ${unit}</strong><small>${comparison(value,previous,unit==='%'?'puncte procentuale':unit)}</small></article>`).join('');
  $('smart-recent').innerHTML=[...new Map([...home.today,...home.recent].map(r=>[r.id,r])).values()].slice(0,8).map(r=>`<div class="smart-record"><div><strong>${esc(names[r.mode])}${r.date===today()?' · astăzi':''}</strong><span>${esc(r.date)} · ${esc(new Date(r.updated_at).toLocaleString('ro-RO'))}</span></div><button type="button" class="secondary-button" data-open-report="${esc(r.id)}">Deschide</button></div>`).join('')||'<p>Încă nu există rapoarte salvate.</p>';
  if(!home.today.length)$('smart-recent').insertAdjacentHTML('afterbegin','<p class="smart-note">Raportul de azi nu este încă salvat. Alege mai jos modulul potrivit.</p>');drawChart();
 }
 function drawChart(){if(!home)return;const metric=$('smart-metric').value,series=home.series,actualMax=Math.max(...series.map(d=>Number(d[metric]||0)),0),max=Math.max(actualMax,1),unit=metric==='percent'?'%':'t',w=Math.max(600,Math.min(900,$('smart-chart').clientWidth)),h=230,step=(w-80)/series.length;
  const bars=series.map((d,i)=>{const x=40+i*step,y=190-Number(d[metric]||0)/max*150;return d[metric]===null?`<text x="${x+step/2}" y="186" text-anchor="middle" class="chart-missing">—</text>`:`<rect x="${x+3}" y="${y}" width="${Math.max(step-6,4)}" height="${Math.max(190-y,2)}" rx="4" class="chart-bar"><title>${esc(d.date)}: ${fmt(d[metric])} ${unit}</title></rect>`;}).join('');
  $('smart-chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc($('smart-metric').selectedOptions[0].text)} pe ${series.length} zile. Valorile exacte sunt în tabelul de mai jos."><line x1="40" y1="190" x2="${w-20}" y2="190" class="chart-axis"/><text x="40" y="24" class="chart-label">Maxim ${fmt(actualMax)} ${unit}</text>${bars}<text x="40" y="219" class="chart-label">${esc(home.start)}</text><text x="${w-20}" y="219" text-anchor="end" class="chart-label">${esc(home.end)}</text></svg>`;
  $('smart-series').innerHTML='<table><thead><tr><th>Data</th><th>Predat (t)</th><th>Backlog (t)</th><th>Deșeu (t)</th><th>Deșeu (%)</th></tr></thead><tbody>'+series.map(d=>`<tr><th>${esc(d.date)}</th>${['handed','backlog','waste','percent'].map(k=>`<td>${d[k]===null?'Lipsă':fmt(d[k])}</td>`).join('')}</tr>`).join('')+'</tbody></table>';
  $('smart-chart-note').textContent=home.note+' Perioada curentă conține '+home.current.count+' zile cu raport, iar precedenta '+home.previous.count+'.';
 }
 async function resume(mode){const server=drafts.get(mode),cached=local.get(mode),d=cached&&(!server||cached.updated_at>server.updated_at)?cached:server;if(!d)return;if(!window.PLUPUI.confirmReplace(mode))return;const copy=structuredClone(d);controller(mode).restoreDraft(copy);if(copy.metadata.id&&Number.isInteger(copy.metadata.version))window.PLUPDashboard.setVersion(copy.metadata.id,copy.metadata.version);window.PLUPDashboard.show(mode);window.PLUPUI.markDirty(mode);status(mode,'Ciornă reluată. Verifică data și valorile înainte de salvarea finală.');}
 async function openReport(id){const r=await request('/api/reports/'+encodeURIComponent(id));if(!window.PLUPUI.confirmReplace(r.mode))return;controller(r.mode).load(r.payload,r.id);window.PLUPDashboard.show(r.mode);window.PLUPUI.markClean(r.mode);clearImport(r.mode);}
 // Assistant panels stay adjacent to the forms; no inferred causes or silent corrections.
 for(const [root,suffix] of [['report-view','report'],['plan-view','plan'],['forecast-view','forecast']]){
  const target=root==='report-view'?$(root).querySelector('.editor'):$(root).querySelector('.plan-panel');
  const section=document.createElement('section');section.className='smart-assistant';section.innerHTML=`<p id="smart-draft-${suffix}" class="smart-note" role="status">Modificările sunt salvate automat ca ciornă.</p><details open><summary>Asistent de verificare și rezumat</summary><p class="smart-note">Verificările semnalează posibile probleme. Tu decizi dacă valorile sunt corecte.</p><button type="button" class="secondary-button" data-check="${suffix}">Verifică raportul</button><p id="smart-check-status-${suffix}" role="status"></p><ul id="smart-warnings-${suffix}"></ul><label class="smart-summary">Rezumat pentru conducere<textarea id="smart-summary-${suffix}" rows="4" readonly placeholder="Completează datele și apasă Verifică raportul."></textarea></label><button type="button" class="text-button" data-copy="${suffix}">Copiază rezumatul</button></details><div id="smart-import-${suffix}" hidden></div>`;target.append(section);
 }
 async function check(suffix){const mode=suffix==='report'?window.PLUPReport.payload().mode:suffix,node=$('smart-check-status-'+suffix),button=document.querySelector(`[data-check=${suffix}]`);button.disabled=true;node.textContent='Se verifică valorile…';try{const submitted=JSON.stringify(controller(mode).payload()),r=await post('/api/smart/check',JSON.parse(submitted));if(JSON.stringify(controller(mode).payload())!==submitted){node.textContent='Datele s-au schimbat. Verifică din nou raportul.';return;}$('smart-warnings-'+suffix).innerHTML=r.warnings.map(w=>`<li>${esc(w.message)}</li>`).join('');$('smart-summary-'+suffix).value=r.summary;node.textContent=r.warnings.length?`${r.warnings.length} aspecte de verificat. ${r.basis}`:'Nu am găsit neconcordanțe în verificările disponibile. '+r.basis;}catch(e){node.textContent=e.message;$('smart-summary-'+suffix).value='';$('smart-warnings-'+suffix).replaceChildren();}finally{button.disabled=false;}}
 function clearImport(mode){const source=imports.get(mode);if(source)URL.revokeObjectURL(source.url);imports.delete(mode);const node=$('smart-import-'+mode);if(node){node.hidden=true;node.replaceChildren();}}
 function showImport(mode,file,payload,review){clearImport(mode);imports.set(mode,{url:URL.createObjectURL(file),original:structuredClone(payload),review:new Set(review)});drawImport(mode);schedule(mode);}
 function drawImport(mode){const source=imports.get(mode);if(!source)return;const node=$('smart-import-'+mode),current=controller(mode).payload();node.hidden=false;const fields=mode==='plan'?['client','product','planned','handed','wire','spool','bar','vane','cable','mi','armored','mf','goods','notes']:['product','km','tons','client','measure','status','notes'];const labels={client:'Client',product:'Produs',planned:'Plan (t)',handed:'Predat (t)',wire:'Sârmă',spool:'Lită',bar:'Bară',vane:'Vane',cable:'Cablat',mi:'M.I.',armored:'Armat',mf:'M.F.',goods:'Marfă',notes:'Observații',km:'KM',tons:'Tone',measure:'Măsurări',status:'Stadiu'};
  node.innerHTML=`<h3>Imagine și date extrase</h3><p class="smart-note">Imaginea rămâne doar în această pagină. În celule: valoarea extrasă / valoarea curentă. Câmpurile incerte sunt marcate „Verifică”.</p><div class="smart-compare"><a href="${source.url}" target="_blank" rel="noopener"><img src="${source.url}" alt="Imaginea sursă importată. Apasă pentru mărire."></a><div class="smart-scroll"><table><thead><tr><th>Rând</th>${fields.map(k=>`<th>${labels[k]}</th>`).join('')}</tr></thead><tbody>${current.rows.map((r,i)=>`<tr><th>${i+1} ${r.material}</th>${fields.map(k=>`<td class="${source.review.has(i+':'+k)?'smart-uncertain':''}"><button type="button" class="smart-cell" data-edit-mode="${mode}" data-edit-row="${i}" data-edit-key="${k}"><span>${esc(source.original.rows[i]?.[k]??'')}</span><strong>${esc(r[k]??'')}</strong>${source.review.has(i+':'+k)?'<small>Verifică</small>':''}</button></td>`).join('')}</tr>`).join('')}</tbody></table></div></div><button class="secondary-button" type="button" data-compare="${mode}">Actualizează comparația</button>`;
 }
 function catalogSuggestions(input){const mode=active();if(!['plan','forecast'].includes(mode))return;let panel=$('smart-catalog');if(!panel){panel=document.createElement('div');panel.id='smart-catalog';panel.className='smart-catalog';panel.setAttribute('aria-label','Sugestii din istoricul confirmat');}input.closest('.plan-field').append(panel);const query=input.value.trim().toLocaleLowerCase('ro');const candidates=catalog.filter(r=>r.material===controller(mode).payload().rows[+input.dataset.index]?.material&&r[input.dataset.key]?.toLocaleLowerCase('ro').includes(query)).slice(0,6);panel.replaceChildren();if(!candidates.length){panel.textContent='Încă nu există sugestii confirmate pentru acest câmp.';return;}for(const r of candidates){const b=document.createElement('button');b.type='button';b.className='secondary-button';b.textContent=`${r.product} · ${r.client||'client necompletat'}${r.measure?' · '+r.measure:''}`;b.addEventListener('click',()=>{const row=input.dataset.index,keys=input.dataset.key==='product'?['product','client',...(mode==='forecast'?['measure']:[])]:['client'];for(const k of keys){const field=document.querySelector(`#${mode}-rows input[data-index="${row}"][data-key="${k}"]`);if(field&&(!field.value.trim()||k===input.dataset.key)){field.value=r[k]||'';field.dispatchEvent(new Event('input',{bubbles:true}));}}panel.remove();input.focus();});panel.append(b);}}
 async function versions(id){let node=$('smart-version-panel');if(!node){node=document.createElement('section');node.id='smart-version-panel';node.className='smart-surface';$('history-view').append(node);}node.innerHTML='<h2>Versiuni ale raportului</h2><p role="status">Se încarcă…</p>';try{const [rows,current]=await Promise.all([request('/api/smart/versions?id='+encodeURIComponent(id)),request('/api/reports/'+encodeURIComponent(id))]);node.innerHTML='<h2>Versiuni ale raportului</h2><p class="smart-note">Restaurarea creează o versiune nouă. Versiunile existente se păstrează. Accesul actual folosește contul aplicației; istoricul nu identifică persoane distincte.</p>';if(!rows.length)node.insertAdjacentHTML('beforeend','<p>Raport anterior activării versiunilor. Prima editare va păstra și versiunea inițială.</p>');for(const row of rows){const item=document.createElement('div');item.className='smart-version';item.innerHTML=`<strong>${row.version===current.version?'Versiunea curentă':'Versiune anterioară'} · ${esc(new Date(row.created_at).toLocaleString('ro-RO'))}</strong><span>${esc(row.payload.date)} · ${esc(names[row.payload.mode])}</span><details><summary>Vezi diferențele față de versiunea curentă</summary><div class="smart-scroll">${diffTable(row.payload,current.payload)}</div></details>`;if(row.version!==current.version){const restore=document.createElement('button');restore.className='secondary-button';restore.textContent='Restaurează această versiune';restore.addEventListener('click',async()=>{if(!confirm('Restaurezi această versiune? Raportul curent rămâne în istoricul versiunilor.'))return;restore.disabled=true;try{await post('/api/smart/restore',{id,version:row.version,expected:current.version});await versions(id);await window.PLUPDashboard.refreshHistory();}catch(e){restore.disabled=false;const msg=document.createElement('p');msg.setAttribute('role','alert');msg.textContent=e.message;item.append(msg);}});item.append(restore);}node.append(item);}node.scrollIntoView({block:'start',behavior:'instant'});}catch(e){node.textContent=e.message;}}
 function diffTable(a,b){const labels={mode:'Tip raport',date:'Data',week:'Săptămâna',incoming:'Intrări metal',material:'Material',product:'Produs',client:'Client',planned:'Metal planificat (t)',handed:'Metal predat (t)',wire:'Sârmă (t)',spool:'Stoc lită (t)',bar:'Stoc fune / bară (km)',vane:'Stoc vane (km)',cable:'Stoc cablat (km)',mi:'Stoc M.I. (km)',armored:'Stoc armat (km)',mf:'Stoc M.F. (km)',goods:'Marfă predată (km)',km:'Kilometri',tons:'Tone',measure:'Măsurări',status:'Stadiu',notes:'Observații',obs:'Observații',al:'Aluminiu predat (t)',cu:'Cupru predat (t)',backlogAl:'Backlog aluminiu (t)',backlogCu:'Backlog cupru (t)',wasteAl:'Deșeu aluminiu (t)',wasteCu:'Deșeu cupru (t)',op_asumreal:'Asumat / realizat',op_status:'Realizat vs status',op_plan:'Realizat vs plan',op_previz:'Previz schimb 1',op_backal:'Backlog AL operațional',op_backcu:'Backlog CU operațional',op_rigid1:'SF Rigid 1',op_rigid2:'SF Rigid 2',op_rigid3:'SF Rigid 3',op_multi1:'SF Multifir 1',op_multi2:'SF Multifir 2',op_niehoff:'SF Niehoff',op_beta3:'SF Beta 3',op_stocal:'Stoc AL',op_stoccu:'Stoc CU'};const label=k=>{const p=k.split('.'),field=labels[p.at(-1)]||p.at(-1);return p[0]==='rows'?'Rândul '+(Number(p[1])+1)+' · '+field:p[0]==='values'?p[1]+' · '+field:field;};const flatten=(value,prefix='',out={})=>{if(value&&typeof value==='object')for(const [k,v] of Object.entries(value))flatten(v,prefix?prefix+'.'+k:k,out);else out[prefix]=String(value??'');return out;};const old=flatten(a),now=flatten(b),keys=[...new Set([...Object.keys(old),...Object.keys(now)])].filter(k=>old[k]!==now[k]);return keys.length?'<table><thead><tr><th>Câmp</th><th>Această versiune</th><th>Curent</th></tr></thead><tbody>'+keys.map(k=>`<tr><th>${esc(label(k))}</th><td>${esc(k==='mode'?names[old[k]]||old[k]:old[k]??'')}</td><td>${esc(k==='mode'?names[now[k]]||now[k]:now[k]??'')}</td></tr>`).join('')+'</tbody></table>':'<p>Date identice cu versiunea curentă.</p>';}
 document.addEventListener('input',e=>{if(e.target.matches('input[data-key],#report-date,#plan-date,#plan-week,#plan-incoming,#forecast-date')){schedule(active());if(['product','client'].includes(e.target.dataset.key))catalogSuggestions(e.target);const suffix=['weekday','weekend'].includes(active())?'report':active();if(suffix){$('smart-summary-'+suffix).value='';$('smart-check-status-'+suffix).textContent='Date schimbate. Verifică din nou înainte de folosirea rezumatului.';}}});
 document.addEventListener('focusin',e=>{if(e.target.matches('input[data-key=product],input[data-key=client]'))catalogSuggestions(e.target);});
 document.addEventListener('change',e=>{if(e.target.matches('#forecast-show-status,input[name=mode]'))schedule(active());});
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.resume)await resume(b.dataset.resume);else if(b.dataset.openReport)await openReport(b.dataset.openReport);else if(b.dataset.check)await check(b.dataset.check);else if(b.dataset.copy){const field=$('smart-summary-'+b.dataset.copy);if(!field.value)return;try{await navigator.clipboard.writeText(field.value);$('smart-check-status-'+b.dataset.copy).textContent='Rezumat copiat. Verifică-l înainte de trimitere.';}catch{field.focus();field.select();$('smart-check-status-'+b.dataset.copy).textContent='Text selectat. Folosește Copiază din meniul telefonului sau Ctrl+C.';}}else if(b.dataset.compare)drawImport(b.dataset.compare);else if(b.dataset.editMode){const input=document.querySelector(`#${b.dataset.editMode}-rows input[data-index="${b.dataset.editRow}"][data-key="${b.dataset.editKey}"]`);input?.scrollIntoView({block:'center',behavior:'instant'});input?.focus();}else if(b.dataset.versions)await versions(b.dataset.versions);else if(b.matches('[data-remove],#add-al,#add-cu,#forecast-add-al,#forecast-add-cu,#undo-plan-row,#undo-forecast-row,#reset-button'))schedule(active());}catch(error){$('smart-dashboard-status').textContent=error.message;}});
 $('smart-period').addEventListener('change',refresh);$('smart-refresh').addEventListener('click',refresh);$('smart-metric').addEventListener('change',drawChart);
 window.PLUPSmart={refresh,saved,async settle(mode){paused.add(mode);clearTimeout(timers.get(mode));await pending.get(mode);},resumeSync(mode){paused.delete(mode);if(local.has(mode))schedule(mode);},showImport,clearImport,changed:mode=>schedule(mode),confirmNew(mode){if(window.PLUPUI.isDirty(mode))return true;return !(drafts.has(mode)||local.has(mode))||confirm('Există o ciornă pentru acest modul. Dacă începi un raport nou, următoarele modificări o vor înlocui. Poți alege Continuă din dashboard pentru a o relua. Începi unul nou?');}};
 void refresh();
})();
